### ISSUE TITLE
Use default Leaflet icon object

### ISSUE THREAD

**Issue by alexpearce** [mpetazzoni/leaflet-gpx#136]
Rather than having to rely on the icon images in this package being present somewhere, one can use [Leaflet's default icon object](https://leafletjs.com/reference.html#icon-default) instead.

```js
const gpx_url = '';
const icon = new L.Icon.Default;
new L.GPX(gpx_url, {
        async: true,
        marker_options: {
            startIcon: icon,
            endIcon: icon,
            wptIcons: {'': icon},
        },
    })
    .on('loaded', (event) => map.fitBounds(event.target.getBounds()))
    .addTo(map);
```

I wondered if it might make sense to change [leaflet-gpx's default icons](https://github.com/mpetazzoni/leaflet-gpx/blob/f446d48935f5f489bd341479c53c2b31c2a32bd5/gpx.js#L49-L52) to leaflet's default icon? This prevents users of the package having to put leaflet-gpx's icons somewhere accessible.

**Comment by pirex360** [comment]
Yes, i agree with this possible change.

**Comment by mjpoo** [comment]
I would also be keen to see this feature. I've created a nice little function to use FontAwesome icons as `L.DivIcon` markers on the map and it would be great to be able to use this approach for GPX waypoints as well. Even being able to use SVG icons rather than bitmaps would be handy. 

In the meantime if anyone knows any workarounds or forks I'd be interested.
